server:
  port: 9090
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: outboundService
          uri: lb://OUTBOUND-SERVICE
          predicates:
            - Path=/outbound/**
        - id: tpldriverService
          uri:  lb://TPL-DRIVER-SERVICE
          predicates:
            - Path=/driver/**
        - id: commonService
          uri: lb://COMMON-SERVICE
          predicates:
            - Path=/common/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: info, health
