server:
  port: 9090
spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway-service
  cloud:
    gateway:
      routes:
        - id: fireServiceApi
          uri: lb://FIRE-SERVICE-API
          predicates:
            - Path=/fire/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: info, health
